# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#<Faction id: nil, name: nil, description: nil, created_at: nil, updated_at: nil>
#<Playstyle id: nil, title: nil, description: nil, created_at: nil, updated_at: nil>
#<FactionPlaystyle id: nil, faction_id: nil, playstyle_id: nil, created_at: nil, updated_at: nil>

shooty = Playstyle.create(title: "Shooty", description: "Every army in the game has some form or another of shooting attacks.\n From the bolt guns of the space marines to the battle cannons of the Leman Russ tanks found within the Astra Militarum, and then more obscure technologies like the shuriken catapults of the Eldar or the gauss flayers of the Necrons, every army can shoot.\nNaturally, the potency or range of that firepower varies from unit to unit in a given army.\nThat being said, the fact remains that some armies in the game are more effective at shooting than others.\nThis is what it means to refer to an army in Warhammer 40,000 as shooty.")
assaulty = Playstyle.create(title: "Assualty", description: "While every army has shooting weapons in the game, some armies are more adept or suited for getting up close and personal with the foe.\nThese kinds of armies have the weapons, tactics, special rules and abilties necessary to end the fight rather quickly once they close in with enemies.\nWhether its the power/force weapon weilding Grey Knights, the potent and swift Blood Angels, or the Orks swarming with numerous troops that offer a tremendous amount of attacks, some armies in Warhammer 40,000 can be considered assaulty.")
monstrous = Playstyle.create(title: "Monstrous", description: "Towering over most units in the game.\nCrushing, stomping, and blasting through every and anything in their path.\nNothing short but the most devasting of weaponry to halt their advance.\nMonstrous creatures pose some of the most viable threats to any army in Warhammer 40,000.\nFrom the Carnifex broods of the Tyranids to the Great Unlcean Ones of the Chaos Daemons, the fact of the matter is, some armies are centered around them and as such, these monstrosities form the basis of battle doctrine for some armies in the game.\nThough rare, monstrous creature centric armies are incedibly formidable fighting forces.")
psyker = Playstyle.create(title: "Psyker", description: "Within the Milky Way Galaxy setting of Warhammer 40,000, their lies a parallel dimension to the reality of space and time known as the Warp.\nIt is the well from which psykers of every race draw their power.\nFrom mind reading, blasts of invisible force, lightening conjured from nothing, or seeing into the future, psykers offer an immense advantage to armies in Warhammer 40,000.\nNot just in an offensive role, psykers can also be used to augment or boost the abilities of their fellow units or allies.\nSome armies are totally void of psykers, such as Tau or Necrons while others are completely built around them such as Eldar or Grey Knights.")
armor = Playstyle.create(title: "Armor", description: "Withstanding the volumous firepower of infantry, able to engage the toughest units, armor is essential in one form or another in any battleforce in the game.\nHowever, some armies offer better forms and variety of tanks and vehicles than others.\nWhile the Eldar and Dark Eldar boast some of the swiftest armor in the game, they don't stand a chance against the Leman Russ tanks of the Astra Militarum or the immense Land Raiders of the Space Marine armies.\nA well formed and potent force of armored units can be the deciding factor between victory or defeat for some armies in Warhammer 40,000.")
mobile = Playstyle.create(title: "Mobile", description: "Speed is an essential facet of warfare.\nThe faster army will always be able to close in on their enemies for the range of their weapons sooner or secure objectives quicker.\nMobile armies will also be able to hone in faster on their opponent for close combat therefore either bogging them down or annihilating them right away.\nCertain armies in the game are faster and more mobile like the Eldar and Dark Eldar or the Ravenwing of the Dark Angels.\nAs a result they will run rings around slower foes such as the Necrons or the Astra Militarum.")
swarm = Playstyle.create(title: "Swarm", description: "Imagine a sea of units flooding over and drowning all in their path.\nRank upon rank of troops exhausting the attacks of the enemy and consumiong its resources and attentions that would be better suited for other things that would actually win the game.\nSome armies in Warhammer 40,000 are able to produce far more numerous and cheaper units compared to other more specialized or elite armies in the game.\nFrom the cannon fodder Gaunts of the Tyranids to the Ork Boyz driven on by the power of the WAGGHHH!!!, certain armies in the game are able to field massive amounts of units to overwhelm the foe.")
elite = Playstyle.create(title: "Elite", description: "They have the best weapons, equipment, and training above all.\nThey are the scalpel that can offer the precision necessary to stop a threat dead in its tracks.\nSome armies in Warhammer 40,000 boast some of the most specialist and elite units in the game.\nWhether it be the assassins of the Inquisition or the ever hunting Ravenwing of the Dark Angels, elite armies have a tool for any job big or small.\nElite elements can table an opponent before they know what hits them in the hands of a skilled player.\nA word of caution, though, elite units are always expensive points-wise and are mostly practiced by experienced veterans of the game.")
support = Playstyle.create(title: "Support", description: "Sometimes, armies just need a helping hand.\nThat helping hand can come in the form of a deepstriking squad of Grey Knight terminators, or groundshaking Imperial Knight, or even the subtleness of an Inquisitor and his retinue.\nArmies that serve mainly as support elements are great at allying with various factions in the game, plugging up holes in a main force's strategy to ensure victory.\nWhile this almost goes hand in hand with an elite playstyle, the structural organization of a support army offers up a great many combinations for coming up with an army that can address almost any threat an opponent brings to the table.")


space_marines = Faction.create(name: "Space Marines", description: "The Space Marines or Adeptus Astartes are foremost amongst the defenders of humanity, the greatest of Mankind's warriors.\n They are superhuman; having been made superior to a normal man by a harsh regime of genetic modification, psycho-conditioning and rigorous training.\n Space Marines are untouched by plague or any natural disease and can suffer wounds that would kill a lesser being several times over, clad in ancient Power Armour and wielding the most potent weapons known to Man.\n The Space Marines as an army offer the most versality out of any army in the game.\n Through their Chapter Tactics as well as array of different space marine chapters, players can customize their space marine army to suit their playstyle needs without sacrificing the durability and power the space marines are known for.\nThe only downside to the army is the fact that their frequency of use has made counter tactics widespread by other potential opponents.\nFurthermore, their units and vehicle can prove to be expensive points-wise, therefore, almost always a space marine player is outnumbered on the battlefield.")
adepta_sororitas = Faction.create(name: "Adepta Sororitas", description: "The Adepta Sororitas, also known as the Sisters of Battle and formerly known as the Daughters of the Emperor, are an all-female division of the Imperial Cult's ecclesiastical Adepta known as the Ecclesiarchy or, more formally, as the Adeptus Ministorum.\n The Sisterhood's Orders Militant serve as the Ecclesiarchy's fighting arm, mercilessly rooting out corruption and heresy within humanity and every organization of the Adeptus Terra.\n With access to relatively the same weapons as the space marine army but with a few nifty HQ choices to gather from, the Adepta Sororitas make a formidable fighting force either as your main detachment or in a support structure role.\n However, they do prove weaker when compared to the choices on display with a space marine army in terms of durability and versatility.\n Also, on the downside, the army structure is very top heavy with the HQ's due to their cheap points cost, which leaves many of your staple troop choices more expensive than for what they're worth.\nThis also presents a steep learning curve for beginner players.")
astra_militarum = Faction.create(name: "Astra Militarum", description: "The Imperial Guard, also known as the Astra Militarum in traditional High Gothic, is the largest coherent fighting force in the galaxy.\n They serve as the Imperium of Man's primary combat force and first line of defence from the myriad threats which threaten the existence of the human race in the late 41st Millennium.\n It is comprised of countless billions of men and women, hundreds of thousands of different regiments, supported by a vast array of light and heavy armoured vehicles that provide the Guard's primary offensive punch.\n The Astra Militarum is the most traditional fighting force in the game, comprised of infantry supported by armor and heavy weapon teams.\n For players looking to field mass units and armor look no further. The downside being many of the units in this aren't as durable as other armies.\nThe upside, they offer some of the best firepower in the game as well as boast the most numerous variants of tanks.\nThis army is always highly recommended as a beginner army due to its familiar force organization.")
eldar = Faction.create(name: "Eldar", description: "The Eldar are an ancient alien race whose vast empire once expanded the width and breadth of the known galaxy.\n Their empire was without equal, and they counted themselves masters of the stars.\n But millennia ago, their overweening pride and their fall into hedonistic practices led to a cataclysm that all but eradicated their kind.\n Though highly advanced and feared across the galaxy, the Eldar are a dying race, teetering on the brink of annihilation.\n The eldar play like a well orchestrated symphony.\n There is a tool for every job, however, all the parts must play in perfect concert.\n For this reason the Eldar present a steep learning curve for beginners and their individual units aren't very durable.\n That being said, they posses some of the most powerful weapons in the game as well as potent psychic power.\n Their army special rules furthermore add to their potency as a fighting force as being some of the most effective in the entire game.")
dark_eldar = Faction.create(name: "Dark Eldar", description: "The Dark Eldar are the forsaken and corrupt kindred of the Eldar.\n Their armies, like their Eldar counterparts, usually have the advantages of mobility and advanced technology, though they are often lacking in resilience and numbers. The Dark Eldar revel in piracy, enslavement and torture, and are sadistic in the extreme. Dark Eldar armies make use of various anti-gravity skimmers such as Raiders and Ravagers to launch high speed attacks.\n Using speed and a heavy emphasis on poison ammunition for their ranged weapons, the Dark Eldar prove to be an interesting army for a player who wants to use tricky and diversive tactics.\n Their Power from Pain abilties also offer nice boosts to the army overall.\nLike their Eldar counterparts, however, they prove frail compared to other armies in the game as well as offer a steep learning curve for beginners due to this fragility and so have to be used with the utmost care in strategy by players.\n While there are elements for close combat in this army, it is often advised against using this army for such tactics due to lack of toughness or viable armor save values.")
orks = Faction.create(name: "Orks", description: "The Orks are a savage, warlike, green-skinned race of humanoids who are spread all across the Milky Way Galaxy.\n They are seen by their enemies (basically everyone else in the universe) as savage, warlike, and crude, but they are the most successful species in the whole galaxy, outnumbering possibly every other intelligent race, even Mankind (with the very plausible exception of the Tyranids).\n Size dominates Ork society and the largest of their kind rise to lead them to battle.\nOn occasion an especially hulking Ork Warlord will conquer several rival groups, forming the survivors into a massive single army.\nWhat follows is known as a WAAAGH!, part invasion and part holy war.\nThe Greenskins will put aside their differences and work together.\nIf you're looking for an army that fields massive numbers of cheap troops who are all durable and can offer many attacks in close combat, as well as possessing a fun satirical falvor, then look no further.\n The downside to this army being their shooting is mediorce in comparison to other armies in the game and when faced with massive firepower their casualties will mount up quickly.")
dark_angels = Faction.create(name: "Dark Angels", description: "The Dark Angels are considered amongst the most powerful and secretive of the Space Marine Chapters.\n They were the first Legion of the original 20 Space Marine Legions to be created during the First Founding of the 30th Millennium.\n Though they claim complete allegiance to Mankind, their actions and secret goals at times seem at odds with that professed loyalty, as the Dark Angels strive above all other things to atone for an ancient crime of betrayal committed over 10,000 standard years ago.\n The Dark Angels are a unique space marine chapter as they are considered elite and specialist in their tactics and army structure.\n For durability and firepower their elite termiantor squad is known as the Deathwing.\n If you favor more speed and mobility then the attack bike centric Ravenwing will prove to your liking.\nEven their standard infantry choice can lay down incredible firepower with their Banner of Devastation.\nWhat's the downside you ask? They prove to be an exspensive army points wise, and so, like most space marine armies, will be outnumbered on the battleifeld.")
necrons = Faction.create(name: "Necrons", description: "The Necrons are a mysterious race of robotic skeletal warriors that have lain dormant in their stasis-tombs for more than 60 million years.\nAt long last, they are beginning to awaken from their Tomb Worlds, for the galaxy is ripe for conquest and the restoration of the Necron Empire.\n The Necrons are a completely robotic humanoid species whose technological prowess is probably unmatched by any of the other intelligent species of the galaxy.\nOut of a desire for vengeance against the more fortunate xenos races in the galaxy, the Necrons shed their original organic forms and lost all forms of compassion and empathy, becoming ruthless, undying killing machines.\nNecrons specialize in abilities and tactics that really mess with the rules of the game, besides the laws of physics and reality.\nFor the player who wants to control a shambling, undead robot army, with interesting weaponry and abilities, the Necrons are right up your alley.\n Be warned, however, for the Necrons suffer at times from lack of mobility and a complete absence of psykers in their army.")
chaos_space_marines = Faction.create(name: "Chaos Space Marines", description: "Chaos Space Marines, also sometimes called Traitor Marines or Renegade Marines, are former Loyalist Space Marines of the Imperium of Man who have chosen to betray the service of the Emperor of Mankind and dedicate their souls to the service of Chaos and its foul deities.\n Such corrupt marines normally belong to one of the 9 Traitor Legions that betrayed the Emperor during the ancient civil war called the Horus Heresy more than 10,000 standard years ago, while others come from Space Marine Chapters created long after the Heresy ended that have turned Renegade.\n Chaos can corrupt Astartes of any time and place just as its siren call leads many lesser men to their damnation.\nThe Chaos Space Marines present all the advantages and disadvantages of their loyalist kin.\nInstead of chapter tactics, however, they pull their tactics and flavor from the gods of chaos, or whichever one a player chooses to adhere to, whether it be the durable Nurgle Plague Marines or the assault driven Khorne Beserkers.")
chaos_daemons = Faction.create(name: "Chaos Daemons", description: "Chaos Daemons, also known as the Neverborn amongst the Forces of Chaos, are intelligent and usually malevolent entities of the Warp, the parallel dimension to the reality of the Milky Way Galaxy, that are living embodiments of Chaos.\n Daemons are collectively the greatest servants of the Chaos Gods and of Chaos itself as a universal force.\n They are created at the whim of one of the four major Chaos Gods from a fraction of the god's own power within the Warp and act as an extension of his will.\n A daemon's appearance and intrinsic character reflect the god's own nature.\nThis army is your typical evil army of nightmares, the enemy of all that is living(Necrons being the exception to living).\nThis army is incedibly psyker and monstrous creature heavy.\nLike the Loyal and Chaos Space Marine chapters, a Chaos Daemon army can be taylored to a player's needs depending on which God they choose to follow, or if the player chooses, mix all four together.\nThis army, however, also suffers from lack of mobility at times.\nTheir units can also prove expensive points wise.")
space_wolves = Faction.create(name: "Space Wolves", description: "The Space Wolves are one of the original 20 First FoundingSpace Marine Legions.\nThe Space Wolves are known for their fiercely anti-authoritarian behaviour. They strongly resist the central command structure of the Imperium, organising themselves into Packs instead of the normal Squads and continue to refuse the dictates of the Codex Astartes, the standardised guide to Space Marine and Imperial Guard tactics.\nThe Space Wolves only accept some standard Imperial tactics that were considered useful for their own preferred style of warfare.\nAs such, they have a reputation for being as ill-disciplined as they are fearless.\nThey are often perceived to be an all-out assault army.\nThis is, however, erroneous, for the Space Wolves have a much more flexible and balanced play style and a greater behavioral reliability than either of the above mentioned Chapters.\nThey do favor shorter-ranged confrontation than the traditional Codex Astartes-compliant Chapters.\nLike all space marine chapters, they suffer from the same disadvantage of being an expensive army and will most lilely be outnumbered on the battlefield.")
blood_angels = Faction.create(name: "Blood Angels", description: "The Blood Angels are one of the 20 First Founding Legions of theSpace Marines.\nThey are well-known across the galaxy for their bloodthirsty nature in battle, and feared for the curse of flawed gene-seedthey carry.\nThe Blood Angels are amongst the longest-living of theAdeptus Astartes, with some of the Chapter's Space Marines having served the Emperor of Mankind for over a thousand standard years.\nThe companies of the Blood Angels generally fight in a similar fashion as most other Space Marine forces, with a tendency toward aggressive and more assault driven tactics.\nThey also employ drop pod and deep strike tactics through their special rules.\nThe Blood Angels also boast some of the strongest dreadnought variants.\nOn the downside, their ranged power is not necessarily notable compared to other armies in the game and the random nature of their Red Thirst ability can yield unexpected results in a player’s strategy.\nLike all space marine armies, the Blood Angels can prove to be expensive points wise and are usually outnumbered in force.")
tau = Faction.create(name: "Tau", description: "The Tau are a young, humanoid and technologically-advanced intelligent race native to the Eastern Fringes of the Milky Way Galaxy who are fighting to expand their interstellar empire and a philosophical concept they call the Greater Good.\nThe Tau claim to be a peaceful race when possible, asking if others will join their cause voluntarily instead of fighting.\nHowever, if their peaceful overtures are refused, the Tau may well decide to conquer a planet and add it to their growing interstellar empire for the greater good.\nIn the game, the Tau are a ranged army.\n They typically have longer ranges and greater firepower than the equivalent weapons of other armies.\nTau armies utilize the inherent mobility and speed of Tau vehicles and battlesuits to confuse and overwhelm the enemy by engaging them at all levels of the battlefield.\nThe Tau also make extensive use of small AI-controlled Drones, typically equipped with guns or shield projectors, these drones can be used to protect teams of Fire Warriors and battlesuits and support vehicles.\nAs such, the Tau have a tremendous weakness towards Close Combat ability, close to almost non existent.")
tyranids = Faction.create(name: "Tyranids", description: "The Tyranids are an extragalactic composite species that is actually a space-faring ecosystem comprised of innumerable different bioforms which are all variations on the same genetic theme.\nThe Tyranid race is ultimately dedicated solely to its own survival, propagation and evolutionary advancement.\nThe Tyranids collectively form a monstrous superorganism that travels across the universe in their great Hive Fleets.\nAll Tyranid organisms are synaptic (psychically-reactive), and each Tyranid creature within a Hive Fleet shares and contributes to a communal Hive Mind, which allows the trillions of beings comprising the Tyranid race to communicate and organise instantaneously on a staggering scale.\nThe Tyranids are your ultimate swarm army.\nAble to field a tremendous amount of cheap and disposable troop units to wear down an opponent’s attacks and bog down their movements, the Tyranids are also supported by a vast array of powerful monstrous creatures.\nTheir main weakness comes in their army’s structure to be dependent on synaptic units.\nLosing a synapse creature, throws those numerous cheap units into disarray from the random Instinct Table, causing headaches for a controlling player.")
grey_knights = Faction.create(name: "Grey Knights", description: "The Grey Knights are a secret, mysterious Loyalist Chapter of Space Marines specifically tasked with combating the dangerous daemonic entities of the Warp and all those who wield the corrupt power of the Chaos Gods.\nThe Grey Knights act as the military arm of the Ordo Malleus, the Daemonhunters who form the oldest branch of the virtually omnipotent Inquisition.\nUnlike other Astartes, every Grey Knight is a potent psyker.\nYet, in the 10,000 standard years of Imperial history, no Grey Knight has ever been corrupted by the Ruinous Powers of Chaos.\nThe presence of potent psykers in Grey Knights squads means that Grey Knights gain immense advantages against Chaotic opposition.\nA Grey Knights force also contains a high proportion of troops who can teleport through the Warp into battle, which can turn the tide of combat if deployed well.\nThe Grey Knights also offer a great support element to other Imperial forces as they can ally with virtually any Imperial army in the game.\nGrey Knights, arguably being the most elite force in the game and therefore the most expensive points wise, leads to its own tactical problems. For all their power, Grey Knights will always be badly outnumbered and must focus upon the fast and lethal application of force.")
inquisition = Faction.create(name: "Inquisition", description: "The Inquisition is a secret organisation that exists outside the standard administrative hierarchy of the Imperium of Man.\nThe Inquisition acts as the secret police force of the Imperium, hunting down any and all of the myriad threats to the stability of Mankind's realm, from the corruption caused by the Forces of Chaos, Heretics, mutants and rebels, to assaults from vicious alien species.\nOften experienced Inquisitors or ones in need of specific services depending on their Ordo or the current situation at hand will have retinues of henchmen that he has deemed most useful.\nThese retinues can be made up of a variety of individuals from Chirurgeon medics to lobotomized Gun Servitors carrying massive heavy weapons.\nLike the Grey Knights, the forces of the Inquisition are more suited to a support element to other Imperial armies while offering a wide variety of units, weaponry and abilities, from xenos weaponry to assassin units.\nWhile not as costly as the Grey Knights, Inquisitors and their retinues prove more frail than the forces they ally with, therefore making it somewhat impractical to make them a main force in their own right.")
imperial_knights = Faction.create(name: "Imperial Knights", description: "An Imperial Knight is a small combat walker that is a one-man version of a Titan.\nThese ancient battlesuits stand thirty to forty feet tall, are protected by nearly impenetrable Ion Shields and armed with a devastating array of heavy weapons.\nKnights come in several variants such as the Lancer, Errant, or Paladin.\nKnights will also fight alongside Astra Militarum, Space Marine and other Imperial forces whenever they feel it is their duty to do so.\nOffering another major support element for Imperial forces, Imperial Knights are an interesting breed of fighting force in the game as they are not considered lords of war, but as such, still amount to the same point cost and fighting capabilities as a super heavy walker or gargantuan creature.\nThey pose a formidable threat to enemies on the battlefield whether through long range or in assault.\nThat doesn’t mean a knight is not without its weaknesses though.\nTheir size deprives them of cover or blocking line of sigh for opponent’s attacks and many anti vehicle tactics can apply to defeating an Imperial Knight.")


FactionPlaystyle.create(faction: space_marines, playstyle: shooty)
FactionPlaystyle.create(faction: space_marines, playstyle: assaulty)
FactionPlaystyle.create(faction: space_marines, playstyle: psyker)
FactionPlaystyle.create(faction: tau, playstyle: shooty)
FactionPlaystyle.create(faction: adepta_sororitas, playstyle: shooty)
FactionPlaystyle.create(faction: adepta_sororitas, playstyle: assaulty)
FactionPlaystyle.create(faction: adepta_sororitas, playstyle: armor)
FactionPlaystyle.create(faction: astra_militarum, playstyle: shooty)
FactionPlaystyle.create(faction: astra_militarum, playstyle: armor)
FactionPlaystyle.create(faction: eldar, playstyle: shooty)
FactionPlaystyle.create(faction: eldar, playstyle: mobile)
FactionPlaystyle.create(faction: eldar, playstyle: psyker)
FactionPlaystyle.create(faction: dark_eldar, playstyle: shooty)
FactionPlaystyle.create(faction: dark_eldar, playstyle: mobile)
FactionPlaystyle.create(faction: orks, playstyle: assaulty)
FactionPlaystyle.create(faction: orks, playstyle: swarm)
FactionPlaystyle.create(faction: dark_angels, playstyle: shooty)
FactionPlaystyle.create(faction: dark_angels, playstyle: mobile)
FactionPlaystyle.create(faction: dark_angels, playstyle: assaulty)
FactionPlaystyle.create(faction: dark_angels, playstyle: elite)
FactionPlaystyle.create(faction: dark_angels, playstyle: psyker)
FactionPlaystyle.create(faction: necrons, playstyle: shooty)
FactionPlaystyle.create(faction: necrons, playstyle: assaulty)
FactionPlaystyle.create(faction: necrons, playstyle: mobile)
FactionPlaystyle.create(faction: chaos_space_marines, playstyle: assaulty)
FactionPlaystyle.create(faction: chaos_space_marines, playstyle: psyker)
FactionPlaystyle.create(faction: chaos_space_marines, playstyle: shooty)
FactionPlaystyle.create(faction: chaos_daemons, playstyle: assaulty)
FactionPlaystyle.create(faction: chaos_daemons, playstyle: monstrous)
FactionPlaystyle.create(faction: chaos_daemons, playstyle: psyker)
FactionPlaystyle.create(faction: space_wolves, playstyle: shooty)
FactionPlaystyle.create(faction: space_wolves, playstyle: assaulty)
FactionPlaystyle.create(faction: space_wolves, playstyle: mobile)
FactionPlaystyle.create(faction: space_wolves, playstyle: psyker)
FactionPlaystyle.create(faction: blood_angels, playstyle: assaulty)
FactionPlaystyle.create(faction: blood_angels, playstyle: mobile)
FactionPlaystyle.create(faction: blood_angels, playstyle: psyker)
FactionPlaystyle.create(faction: tyranids, playstyle: swarm)
FactionPlaystyle.create(faction: tyranids, playstyle: assaulty)
FactionPlaystyle.create(faction: tyranids, playstyle: psyker)
FactionPlaystyle.create(faction: tyranids, playstyle: monstrous)
FactionPlaystyle.create(faction: grey_knights, playstyle: assaulty)
FactionPlaystyle.create(faction: grey_knights, playstyle: psyker)
FactionPlaystyle.create(faction: grey_knights, playstyle: elite)
FactionPlaystyle.create(faction: grey_knights, playstyle: support)
FactionPlaystyle.create(faction: inquisition, playstyle: psyker)
FactionPlaystyle.create(faction: inquisition, playstyle: elite)
FactionPlaystyle.create(faction: inquisition, playstyle: support)
FactionPlaystyle.create(faction: imperial_knights, playstyle: support)
FactionPlaystyle.create(faction: imperial_knights, playstyle: armor)
FactionPlaystyle.create(faction: imperial_knights, playstyle: elite)
FactionPlaystyle.create(faction: imperial_knights, playstyle: assaulty)

















